apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    name: result
    app: result
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001

